import type {
  Student,
  Teacher,
  Notice,
  Project,
  Attendance,
  TeacherCredentials,
} from "./types";

// Default teacher credentials
export const DEFAULT_TEACHER_CREDENTIALS: TeacherCredentials[] = [
  { id: "1", teacherId: "1", username: "amit.kumar", password: "teacher123" },
  { id: "2", teacherId: "2", username: "suman.roy", password: "teacher123" },
  { id: "3", teacherId: "3", username: "rajesh.singh", password: "teacher123" },
  { id: "4", teacherId: "4", username: "priya.das", password: "teacher123" },
  { id: "5", teacherId: "5", username: "sunil.mondal", password: "teacher123" },
];

// Default data with more students per department
export const DEFAULT_STUDENTS: Student[] = [
  // CSE Students - different semesters
  {
    id: "1",
    name: "Rahul Sharma",
    email: "34900122001@cgec.ac.in",
    rollNumber: "34900122001",
    department: "Computer Science & Engineering",
    semester: 6,
    phone: "9876543210",
    address: "Coochbehar, West Bengal",
    dateOfBirth: "2003-05-15",
    admissionYear: 2022,
    guardianName: "Mr. Sharma",
    guardianPhone: "9876543211",
    status: "active",
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: "2",
    name: "Amit Das",
    email: "34900123015@cgec.ac.in",
    rollNumber: "34900123015",
    department: "Computer Science & Engineering",
    semester: 4,
    phone: "9876543220",
    address: "Alipurduar, West Bengal",
    dateOfBirth: "2004-08-22",
    admissionYear: 2023,
    guardianName: "Mr. Das",
    guardianPhone: "9876543221",
    status: "active",
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: "3",
    name: "Priya Sen",
    email: "34900124010@cgec.ac.in",
    rollNumber: "34900124010",
    department: "Computer Science & Engineering",
    semester: 2,
    phone: "9876543230",
    address: "Jalpaiguri, West Bengal",
    dateOfBirth: "2005-03-10",
    admissionYear: 2024,
    guardianName: "Mr. Sen",
    guardianPhone: "9876543231",
    status: "active",
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  // ECE Students
  {
    id: "4",
    name: "Sneha Roy",
    email: "34900222005@cgec.ac.in",
    rollNumber: "34900222005",
    department: "Electronics & Communication Engineering",
    semester: 6,
    phone: "9876543240",
    address: "Siliguri, West Bengal",
    dateOfBirth: "2003-06-18",
    admissionYear: 2022,
    guardianName: "Mr. Roy",
    guardianPhone: "9876543241",
    status: "active",
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: "5",
    name: "Ravi Mondal",
    email: "34900223020@cgec.ac.in",
    rollNumber: "34900223020",
    department: "Electronics & Communication Engineering",
    semester: 4,
    phone: "9876543250",
    address: "Malda, West Bengal",
    dateOfBirth: "2004-09-25",
    admissionYear: 2023,
    guardianName: "Mr. Mondal",
    guardianPhone: "9876543251",
    status: "active",
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  // EE Students
  {
    id: "6",
    name: "Ananya Ghosh",
    email: "34901622008@cgec.ac.in",
    rollNumber: "34901622008",
    department: "Electrical Engineering",
    semester: 6,
    phone: "9876543260",
    address: "Durgapur, West Bengal",
    dateOfBirth: "2003-01-12",
    admissionYear: 2022,
    guardianName: "Mr. Ghosh",
    guardianPhone: "9876543261",
    status: "active",
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: "7",
    name: "Sourav Banerjee",
    email: "34901624012@cgec.ac.in",
    rollNumber: "34901624012",
    department: "Electrical Engineering",
    semester: 2,
    phone: "9876543270",
    address: "Kolkata, West Bengal",
    dateOfBirth: "2005-04-08",
    admissionYear: 2024,
    guardianName: "Mr. Banerjee",
    guardianPhone: "9876543271",
    status: "active",
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  // ME Students
  {
    id: "8",
    name: "Dipak Sarkar",
    email: "34900423003@cgec.ac.in",
    rollNumber: "34900423003",
    department: "Mechanical Engineering",
    semester: 4,
    phone: "9876543280",
    address: "Asansol, West Bengal",
    dateOfBirth: "2004-07-20",
    admissionYear: 2023,
    guardianName: "Mr. Sarkar",
    guardianPhone: "9876543281",
    status: "active",
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  // CE Students
  {
    id: "9",
    name: "Moumita Dey",
    email: "34900522018@cgec.ac.in",
    rollNumber: "34900522018",
    department: "Civil Engineering",
    semester: 6,
    phone: "9876543290",
    address: "Howrah, West Bengal",
    dateOfBirth: "2003-11-30",
    admissionYear: 2022,
    guardianName: "Mr. Dey",
    guardianPhone: "9876543291",
    status: "active",
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: "10",
    name: "Rajesh Paul",
    email: "34900525007@cgec.ac.in",
    rollNumber: "34900525007",
    department: "Civil Engineering",
    semester: 1,
    phone: "9876543300",
    address: "Murshidabad, West Bengal",
    dateOfBirth: "2006-02-14",
    admissionYear: 2025,
    guardianName: "Mr. Paul",
    guardianPhone: "9876543301",
    status: "active",
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
];

export const DEFAULT_TEACHERS: Teacher[] = [
  // Existing test teachers
  {
    id: "1",
    name: "Dr. Amit Kumar",
    email: "amit.kumar@cgec.ac.in",
    employeeId: "FAC001",
    department: "Computer Science & Engineering",
    designation: "Associate Professor",
    phone: "9876543100",
    qualification: "Ph.D. in Computer Science",
    specialization: "Machine Learning",
    joiningDate: "2018-07-01",
    status: "active",
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: "2",
    name: "Prof. Suman Roy",
    email: "suman.roy@cgec.ac.in",
    employeeId: "FAC002",
    department: "Electronics & Communication Engineering",
    designation: "Assistant Professor",
    phone: "9876543101",
    qualification: "M.Tech in VLSI",
    specialization: "Digital Signal Processing",
    joiningDate: "2019-01-15",
    status: "active",
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: "3",
    name: "Dr. Rajesh Singh",
    email: "rajesh.singh@cgec.ac.in",
    employeeId: "FAC003",
    department: "Electrical Engineering",
    designation: "Professor",
    phone: "9876543102",
    qualification: "Ph.D. in Power Systems",
    specialization: "Power Electronics",
    joiningDate: "2015-08-01",
    status: "active",
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: "4",
    name: "Prof. Priya Das",
    email: "priya.das@cgec.ac.in",
    employeeId: "FAC004",
    department: "Mechanical Engineering",
    designation: "Assistant Professor",
    phone: "9876543103",
    qualification: "M.Tech in Thermal Engineering",
    specialization: "Heat Transfer",
    joiningDate: "2020-01-10",
    status: "active",
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: "5",
    name: "Dr. Sunil Mondal",
    email: "sunil.mondal@cgec.ac.in",
    employeeId: "FAC005",
    department: "Civil Engineering",
    designation: "Associate Professor",
    phone: "9876543104",
    qualification: "Ph.D. in Structural Engineering",
    specialization: "Concrete Structures",
    joiningDate: "2017-06-15",
    status: "active",
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },

  // CSE
  {
    id: "6",
    name: "Mr. Somen Mondal",
    email: "somen.mondal@cgec.ac.in",
    employeeId: "CSE001",
    department: "Computer Science & Engineering",
    designation: "HOD & Assistant Professor",
    phone: "9876543106",
    qualification: "M.Tech",
    specialization: "Cloud Computing",
    joiningDate: "2016-08-16",
    status: "active",
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: "7",
    name: "Mr. Arnab Gain",
    email: "arnab.gain@cgec.ac.in",
    employeeId: "CSE002",
    department: "Computer Science & Engineering",
    designation: "Assistant Professor",
    phone: "9876543107",
    qualification: "M.E.",
    specialization: "Computer Vision",
    joiningDate: "2021-01-01",
    status: "active",
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: "8",
    name: "Dr. Prabir Kr. Naskar",
    email: "prabir.naskar@cgec.ac.in",
    employeeId: "CSE003",
    department: "Computer Science & Engineering",
    designation: "Assistant Professor",
    phone: "9876543108",
    qualification: "Ph.D.",
    specialization: "Cryptography",
    joiningDate: "2010-01-01",
    status: "active",
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: "9",
    name: "Dr. Sourav De",
    email: "sourav.de@cgec.ac.in",
    employeeId: "CSE004",
    department: "Computer Science & Engineering",
    designation: "Assistant Professor",
    phone: "9876543109",
    qualification: "Ph.D.",
    specialization: "Machine Learning",
    joiningDate: "2019-01-01",
    status: "active",
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: "10",
    name: "Mr. Sudip Adhikari",
    email: "sudip.adhikari@cgec.ac.in",
    employeeId: "CSE005",
    department: "Computer Science & Engineering",
    designation: "Assistant Professor",
    phone: "9876543110",
    qualification: "M.Tech",
    specialization: "Image Processing",
    joiningDate: "2019-01-01",
    status: "active",
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: "11",
    name: "Mr. Sukhendu Shekhar Mondal",
    email: "sukhendu.mondal@cgec.ac.in",
    employeeId: "CSE006",
    department: "Computer Science & Engineering",
    designation: "Assistant Professor",
    phone: "9876543111",
    qualification: "M.Tech",
    specialization: "Computer Science",
    joiningDate: "2019-01-01",
    status: "active",
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },

  // ECE
  {
    id: "12",
    name: "Dr. Palash Das",
    email: "palash.das@cgec.ac.in",
    employeeId: "ECE001",
    department: "Electronics & Communication Engineering",
    designation: "HOD & Assistant Professor",
    phone: "9876543112",
    qualification: "Ph.D.",
    specialization: "Electronics",
    joiningDate: "2016-01-01",
    status: "active",
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: "13",
    name: "Dr. Aritra Acharyya",
    email: "aritra.acharyya@cgec.ac.in",
    employeeId: "ECE002",
    department: "Electronics & Communication Engineering",
    designation: "Assistant Professor",
    phone: "9876543113",
    qualification: "Ph.D.",
    specialization: "Nanoelectronics",
    joiningDate: "2018-01-01",
    status: "active",
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: "14",
    name: "Mr. Malay Narayan Das",
    email: "malay.das@cgec.ac.in",
    employeeId: "ECE003",
    department: "Electronics & Communication Engineering",
    designation: "Assistant Professor",
    phone: "9876543114",
    qualification: "M.Tech",
    specialization: "Communication",
    joiningDate: "2018-01-01",
    status: "active",
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: "15",
    name: "Prof. Rajib Das",
    email: "rajib.das@cgec.ac.in",
    employeeId: "ECE004",
    department: "Electronics & Communication Engineering",
    designation: "Assistant Professor",
    phone: "9163309694",
    qualification: "M.Tech",
    specialization: "Electronics",
    joiningDate: "2018-01-01",
    status: "active",
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },

  // ME
  {
    id: "16",
    name: "Dr. Sushovan Chatterjee",
    email: "sushovan.chatterjee@cgec.ac.in",
    employeeId: "ME001",
    department: "Mechanical Engineering",
    designation: "Principal & Associate Professor",
    phone: "9876543116",
    qualification: "Ph.D.",
    specialization: "Mechanical Engineering",
    joiningDate: "2016-01-01",
    status: "active",
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: "17",
    name: "Mr. Gyan Tshering Lepcha",
    email: "gyan.lepcha@cgec.ac.in",
    employeeId: "ME002",
    department: "Mechanical Engineering",
    designation: "Assistant Professor",
    phone: "9876543117",
    qualification: "M.Tech",
    specialization: "Fluid Mechanics",
    joiningDate: "2018-01-01",
    status: "active",
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: "18",
    name: "Prof. Masud Rana",
    email: "masud.rana@cgec.ac.in",
    employeeId: "ME003",
    department: "Mechanical Engineering",
    designation: "Assistant Professor",
    phone: "9851012790",
    qualification: "M.Tech",
    specialization: "Mechanical Engineering",
    joiningDate: "2018-01-01",
    status: "active",
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },

  // EE
  {
    id: "19",
    name: "Dr. Provas Kumar Roy",
    email: "provas.roy@cgec.ac.in",
    employeeId: "EE001",
    department: "Electrical Engineering",
    designation: "Professor",
    phone: "9876543119",
    qualification: "Ph.D.",
    specialization: "Power Systems",
    joiningDate: "2016-01-01",
    status: "active",
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: "20",
    name: "Prof. Atanu Maji",
    email: "atanu.maji@cgec.ac.in",
    employeeId: "EE002",
    department: "Electrical Engineering",
    designation: "Assistant Professor",
    phone: "9734762149",
    qualification: "M.Tech",
    specialization: "Electrical Engineering",
    joiningDate: "2018-01-01",
    status: "active",
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },

  // CE
  {
    id: "21",
    name: "Dr. Kingshuk Dan",
    email: "kingshuk.dan@cgec.ac.in",
    employeeId: "CE001",
    department: "Civil Engineering",
    designation: "Assistant Professor",
    phone: "9876543121",
    qualification: "Ph.D.",
    specialization: "Civil Engineering",
    joiningDate: "2016-01-01",
    status: "active",
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: "22",
    name: "Prof. Chhandamay Ray",
    email: "chhandamay.ray@cgec.ac.in",
    employeeId: "CE002",
    department: "Civil Engineering",
    designation: "Assistant Professor",
    phone: "9903194589",
    qualification: "M.Tech",
    specialization: "Civil Engineering",
    joiningDate: "2018-01-01",
    status: "active",
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },

  // BSH
  {
    id: "23",
    name: "Dr. Samik Nag",
    email: "samik.nag@cgec.ac.in",
    employeeId: "BSH001",
    department: "Basic Science & Humanities",
    designation: "Assistant Professor",
    phone: "9876543123",
    qualification: "Ph.D.",
    specialization: "Chemistry",
    joiningDate: "2016-01-01",
    status: "active",
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: "24",
    name: "Mohammad Salim",
    email: "mohammad.salim@cgec.ac.in",
    employeeId: "BSH002",
    department: "Basic Science & Humanities",
    designation: "Assistant Professor",
    phone: "9876543124",
    qualification: "M.Sc",
    specialization: "Mathematics",
    joiningDate: "2018-01-01",
    status: "active",
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: "25",
    name: "Mr. Arghya Chakraborty",
    email: "arghya.chakraborty@cgec.ac.in",
    employeeId: "BSH003",
    department: "Basic Science & Humanities",
    designation: "Assistant Professor",
    phone: "8617455414",
    qualification: "M.A.",
    specialization: "English",
    joiningDate: "2018-01-01",
    status: "active",
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: "26",
    name: "Mr. Tanmoy Pal",
    email: "tanmoy.pal@cgec.ac.in",
    employeeId: "CSE007",
    department: "Computer Science & Engineering",
    designation: "Assistant Professor",
    phone: "9876543126",
    qualification: "M.Tech",
    specialization: "Computer Science",
    joiningDate: "2020-01-01",
    status: "active",
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
];

export const DEFAULT_NOTICES: Notice[] = [
  {
    id: "1",
    title: "Mid-Semester Examination Schedule",
    content:
      "Mid-semester examinations for all departments will commence from March 15, 2024.",
    category: "exam",
    publishedAt: new Date().toISOString(),
    expiresAt: null,
    isActive: true,
  },
];

export const DEFAULT_PROJECTS: Project[] = [
  {
    id: "1",
    title: "Smart Campus Management System",
    description:
      "An IoT-based system for managing campus resources efficiently.",
    studentIds: ["1"],
    studentNames: ["Rahul Sharma"],
    technologies: ["React", "Node.js", "IoT", "MongoDB"],
    department: "Computer Science & Engineering",
    year: 2024,
    status: "completed",
    githubUrl: "https://github.com/example/smart-campus",
    websiteUrl: "https://smart-campus.example.com",
  },
];
