export const SUBJECTS_BY_DEPARTMENT: Record<string, string[]> = {
  "Computer Science & Engineering": [
    "Data Structures & Algorithms",
    "Computer Organization & Architecture",
    "Operating Systems",
    "Database Management Systems",
    "Design & Analysis of Algorithms",
    "Computer Networks",
    "Software Engineering",
    "Compiler Design",
    "Theory of Computation",
    "Artificial Intelligence",
    "Machine Learning",
    "Web Technology",
    "Computer Graphics",
    "Distributed Systems",
    "Cloud Computing",
    "Information Security",
    "Object Oriented Programming",
    "Digital Logic Design",
    "Discrete Mathematics",
  ],
  "Electronics & Communication Engineering": [
    "Electronic Devices & Circuits",
    "Digital Electronics",
    "Analog Communication",
    "Digital Communication",
    "Signals & Systems",
    "Microprocessors & Microcontrollers",
    "Electromagnetic Theory",
    "Control Systems",
    "Digital Signal Processing",
    "VLSI Design",
    "Antenna & Wave Propagation",
    "Wireless Communication",
    "Optical Communication",
    "Embedded Systems",
    "Satellite Communication",
    "Information Theory & Coding",
  ],
  "Electrical Engineering": [
    "Electrical Circuit Theory",
    "Electrical Machines I",
    "Electrical Machines II",
    "Power Systems I",
    "Power Systems II",
    "Control Systems",
    "Power Electronics",
    "Electrical Measurements & Instrumentation",
    "Digital Electronics",
    "Microprocessors",
    "High Voltage Engineering",
    "Renewable Energy Systems",
    "Electric Drives",
    "Power System Protection",
    "Signal Processing",
  ],
  "Mechanical Engineering": [
    "Engineering Mechanics",
    "Thermodynamics",
    "Fluid Mechanics",
    "Strength of Materials",
    "Manufacturing Processes",
    "Machine Design",
    "Heat Transfer",
    "Theory of Machines",
    "Internal Combustion Engines",
    "Refrigeration & Air Conditioning",
    "Power Plant Engineering",
    "Automobile Engineering",
    "CAD/CAM",
    "Industrial Engineering",
    "Mechatronics",
  ],
  "Civil Engineering": [
    "Engineering Mechanics",
    "Solid Mechanics",
    "Fluid Mechanics",
    "Surveying",
    "Building Materials & Construction",
    "Structural Analysis",
    "Design of RC Structures",
    "Design of Steel Structures",
    "Geotechnical Engineering",
    "Transportation Engineering",
    "Environmental Engineering",
    "Water Resources Engineering",
    "Construction Management",
    "Concrete Technology",
    "Hydraulics",
  ],
  "Basic Science & Humanities": [
    "Engineering Mathematics I",
    "Engineering Mathematics II",
    "Engineering Physics",
    "Engineering Chemistry",
    "Professional Communication",
    "Environmental Science",
    "Economics for Engineers",
  ],
};
